//! Core data structures for folder organization workflow.
//!
//! This module defines the key types that flow through the smartfolder system:
//! - **Scanning phase**: `FileInventoryRecord` and `ScanWarning`
//! - **Planning phase**: `PlanRecord`, `PlanOperation`, and related enums
//! - **Execution phase**: `TransactionJournal`, `TransactionOperation`, and operation statuses

use std::path::PathBuf;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Current version of the plan record schema. Used for format compatibility checking.
pub const PLAN_SCHEMA_VERSION: u16 = 1;

/// Current version of the journal record schema. Used for format compatibility checking.
pub const JOURNAL_SCHEMA_VERSION: u16 = 1;

/// Snapshot of a file collected during directory scanning.
///
/// Created by the scanner module, this record contains all metadata needed to:
/// - Classify the file (by type, extension, date, size)
/// - Apply organization rules
/// - Track the file through subsequent phases
///
/// # Fields
///
/// - `file_id`: Normalized relative path (forward slashes) for consistent reference
/// - `root_relative_path`: Path relative to scan root (platform-specific separators)
/// - `detected_type`: Category determined from extension and entry kind
/// - `entry_kind`: File, directory, symlink, or other special type
/// - `depth`: Nesting level (0 = root items)
/// - `scan_warnings`: Issues encountered reading this file's metadata
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FileInventoryRecord {
    pub file_id: String,
    pub root_relative_path: PathBuf,
    pub name: String,
    pub extension: Option<String>,
    pub detected_type: FileTypeBucket,
    pub size_bytes: u64,
    pub created_at: Option<DateTime<Utc>>,
    pub modified_at: Option<DateTime<Utc>>,
    pub accessed_at: Option<DateTime<Utc>>,
    pub depth: usize,
    pub entry_kind: FileEntryKind,
    pub scan_warnings: Vec<ScanWarning>,
}

/// Broad file type classification based on extension and entry kind.
///
/// Used by built-in sorting rules to organize files into predictable categories.
/// Determined from file extension with fallback based on entry kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileTypeBucket {
    Document,
    Image,
    Video,
    Audio,
    Archive,
    Spreadsheet,
    Presentation,
    Code,
    Directory,
    Link,
    Other,
}

/// The type of file system entry (file, directory, symlink, etc.).
///
/// Determined from metadata to distinguish between regular files, directories,
/// symbolic links, and Windows junctions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileEntryKind {
    File,
    Directory,
    Symlink,
    Junction,
    Other,
}

/// A warning encountered while scanning a file or directory.
///
/// Warnings don't stop the scan but are collected to inform the user
/// about files that couldn't be fully processed or were skipped.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ScanWarning {
    pub code: ScanWarningCode,
    pub path: Option<PathBuf>,
    pub message: String,
}

/// Classification of scan warning types.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ScanWarningCode {
    UnreadableEntry,
    UnsupportedMetadata,
    SkippedByPolicy,
    SpecialFolder,
}

/// Complete plan for organizing files in a directory.
///
/// Generated by the planner phase, a plan contains:
/// - A list of `operations` to be executed (each with conflict detection)
/// - `ambiguous_files` that couldn't be classified
/// - Warnings and a summary of the proposed changes
///
/// Plans are serializable to JSON and can be reviewed, edited, and applied later.
/// Each operation is marked as "selected" based on conflict analysis; only selected
/// operations are applied during execution.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanRecord {
    pub schema_version: u16,
    pub plan_id: String,
    pub root: PathBuf,
    pub mode: PlanMode,
    pub created_at: DateTime<Utc>,
    pub operations: Vec<PlanOperation>,
    pub ambiguous_files: Vec<PathBuf>,
    pub warnings: Vec<PlanWarning>,
    pub summary: PlanSummary,
}

impl PlanRecord {
    /// Create a new empty plan with schema version and metadata.
    pub fn new(
        plan_id: impl Into<String>,
        root: impl Into<PathBuf>,
        mode: PlanMode,
        created_at: DateTime<Utc>,
    ) -> Self {
        Self {
            schema_version: PLAN_SCHEMA_VERSION,
            plan_id: plan_id.into(),
            root: root.into(),
            mode,
            created_at,
            operations: Vec::new(),
            ambiguous_files: Vec::new(),
            warnings: Vec::new(),
            summary: PlanSummary::default(),
        }
    }

    /// Serialize the plan to formatted JSON.
    pub fn to_pretty_json(&self) -> crate::Result<String> {
        serde_json::to_string_pretty(self).map_err(Into::into)
    }
}

/// The classification mode used to generate a plan.
///
/// Can be based on built-in heuristics (type, date, extension)
/// or a custom rule profile loaded from a TOML file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanMode {
    BuiltIn(BuiltInMode),
    RuleProfile { profile_id: String },
}

/// Built-in organization modes available without custom configuration.
///
/// - `Type`: Organize by file type (Document, Image, Video, etc.)
/// - `Date`: Organize by creation/modification year and month
/// - `Extension`: Organize by file extension
/// - `TypeYear`: Combine type and year (e.g., Documents/2024)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BuiltInMode {
    Type,
    Date,
    Extension,
    TypeYear,
}

/// A single move operation proposed by the planner.
///
/// Each operation corresponds to one file being moved from `source` to `destination`.
/// The `conflict` field indicates if the operation is safe to execute.
/// The `selected` field indicates if it will be applied (true if `conflict` is `None`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanOperation {
    pub operation_id: String,
    pub operation_type: OperationType,
    pub source: PathBuf,
    pub destination: PathBuf,
    pub reason: String,
    pub certainty: Certainty,
    pub conflict: ConflictState,
    pub selected: bool,
    pub source_snapshot: SourceSnapshot,
}

/// Type of file system operation (currently only Move is supported).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OperationType {
    Move,
}

/// Confidence level in the proposed operation.
///
/// Indicates how certain the planner is that the proposed destination is correct.
/// Used for user feedback and filtering in advanced interfaces.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Certainty {
    High,
    Medium,
    Low,
}

/// Conflict detection result for a proposed operation.
///
/// - `None`: No conflicts; the operation is safe and will be applied.
/// - `DestinationExists`: File already exists at destination.
/// - `CaseOnlyRename`: Destination differs only in case (may fail on case-insensitive systems).
/// - `UnsafeDestination`: Destination path fails safety checks (e.g., escapes root).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "state")]
pub enum ConflictState {
    None,
    DestinationExists { path: PathBuf },
    CaseOnlyRename { path: PathBuf },
    UnsafeDestination { reason: String },
}

/// Metadata snapshot of a file at plan time.
///
/// Stored with each operation to detect if the file changed before execution,
/// which would invalidate the operation (e.g., deleted or modified).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceSnapshot {
    pub size_bytes: u64,
    pub modified_at: Option<DateTime<Utc>>,
}

/// Summary statistics of a plan for user feedback.
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanSummary {
    pub files_scanned: usize,
    pub moves_proposed: usize,
    pub ambiguous_files: usize,
    pub conflicts: usize,
    pub skipped: usize,
}

/// A warning generated during plan creation.
///
/// Warnings indicate issues like:
/// - Files in cloud-synced folders (risky to reorganize)
/// - Files in special system folders
/// - Unclassified files that couldn't be matched to rules
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanWarning {
    pub code: PlanWarningCode,
    pub message: String,
}

/// Classification of warning types produced during plan generation.
///
/// - `CloudFolder`: Root or file is inside a cloud-synced folder (OneDrive, Dropbox, etc.)
/// - `SpecialFolder`: Root contains system-managed or protected sub-directories
/// - `ExclusionsApplied`: One or more exclusion rules were active during the scan
/// - `AmbiguousFiles`: Some files could not be matched to any rule
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanWarningCode {
    CloudFolder,
    SpecialFolder,
    ExclusionsApplied,
    AmbiguousFiles,
}

/// Record of a file organization transaction for audit and rollback.
///
/// Created when a plan is applied, this journal tracks:
/// - Which operations were attempted
/// - The outcome of each operation (success, skip, failure)
/// - Errors encountered
/// - Overall transaction status
///
/// Journals are persisted to disk and can be inspected or used to undo changes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TransactionJournal {
    pub schema_version: u16,
    pub transaction_id: String,
    pub plan_id: String,
    pub root: PathBuf,
    pub status: TransactionStatus,
    pub started_at: DateTime<Utc>,
    pub completed_at: Option<DateTime<Utc>>,
    pub operations: Vec<TransactionOperation>,
}

impl TransactionJournal {
    /// Create a new empty journal with schema version and metadata.
    pub fn new(
        transaction_id: impl Into<String>,
        plan_id: impl Into<String>,
        root: impl Into<PathBuf>,
        started_at: DateTime<Utc>,
    ) -> Self {
        Self {
            schema_version: JOURNAL_SCHEMA_VERSION,
            transaction_id: transaction_id.into(),
            plan_id: plan_id.into(),
            root: root.into(),
            status: TransactionStatus::InProgress,
            started_at,
            completed_at: None,
            operations: Vec::new(),
        }
    }

    /// Serialize the journal to formatted JSON.
    pub fn to_pretty_json(&self) -> crate::Result<String> {
        serde_json::to_string_pretty(self).map_err(Into::into)
    }
}

/// Overall status of a transaction.
///
/// - `InProgress`: Transaction is currently being executed
/// - `Completed`: All operations completed successfully
/// - `Interrupted`: User cancelled during execution
/// - `RolledBack`: All completed operations were successfully undone
/// - `PartiallyRolledBack`: Some operations were undone, others failed to undo
/// - `Failed`: Fatal error during execution or undo
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TransactionStatus {
    InProgress,
    Completed,
    Interrupted,
    RolledBack,
    PartiallyRolledBack,
    Failed,
}

/// Record of a single move operation executed as part of a transaction.
///
/// Tracks whether the operation succeeded, failed, was skipped, or rolled back,
/// along with any error messages and metadata about the move (e.g., same-volume detection).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TransactionOperation {
    pub operation_id: String,
    pub operation_type: OperationType,
    pub source: PathBuf,
    pub destination: PathBuf,
    pub status: OperationStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub same_volume: Option<bool>,
    pub error: Option<OperationError>,
}

/// Status of a single file move operation.
///
/// - `Pending`: Not yet attempted
/// - `Completed`: File successfully moved
/// - `Skipped`: Not applied (due to conflict or cancellation)
/// - `Failed`: Attempted but encountered an error
/// - `RolledBack`: Successfully undone by undo operation
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OperationStatus {
    Pending,
    Completed,
    Skipped,
    Failed,
    RolledBack,
}

/// Error detail for a failed operation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OperationError {
    pub code: OperationErrorCode,
    pub message: String,
}

/// Classification of errors that can occur during operation execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OperationErrorCode {
    SourceMissing,
    SourceChanged,
    DestinationExists,
    PermissionDenied,
    IoError,
    Cancelled,
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use chrono::Utc;

    use super::{
        BuiltInMode, PlanMode, PlanRecord, TransactionJournal, JOURNAL_SCHEMA_VERSION,
        PLAN_SCHEMA_VERSION,
    };

    #[test]
    fn plan_record_round_trips_with_schema_version() {
        let plan = PlanRecord::new(
            "plan_test",
            PathBuf::from("C:\\data"),
            PlanMode::BuiltIn(BuiltInMode::Type),
            Utc::now(),
        );

        let json = serde_json::to_string(&plan).expect("plan should serialize");
        let restored: PlanRecord = serde_json::from_str(&json).expect("plan should deserialize");

        assert_eq!(restored.schema_version, PLAN_SCHEMA_VERSION);
        assert_eq!(restored.plan_id, "plan_test");
        assert_eq!(restored.mode, PlanMode::BuiltIn(BuiltInMode::Type));
    }

    #[test]
    fn journal_round_trips_with_schema_version() {
        let journal = TransactionJournal::new(
            "txn_test",
            "plan_test",
            PathBuf::from("C:\\data"),
            Utc::now(),
        );

        let json = serde_json::to_string(&journal).expect("journal should serialize");
        let restored: TransactionJournal =
            serde_json::from_str(&json).expect("journal should deserialize");

        assert_eq!(restored.schema_version, JOURNAL_SCHEMA_VERSION);
        assert_eq!(restored.transaction_id, "txn_test");
        assert_eq!(restored.plan_id, "plan_test");
    }
}
